"""
main.py — FastAPI application entry point.

Start the server:
  cd /path/to/college-admissions-market
  pip install -r market/requirements.txt
  uvicorn market.api.main:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI/Swagger):
  http://localhost:8000/docs

Alternative JSON schema explorer:
  http://localhost:8000/redoc
"""

import os
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from market.api.routes import markets, trades, users
from market.db.session import create_tables


# ──────────────────────────────────────────────────────────
# Startup / shutdown lifecycle
# ──────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs once on startup: ensure all DB tables exist.
    SQLAlchemy's `create_all` is idempotent — it only creates missing tables,
    never drops or alters existing ones.
    """
    await create_tables()
    print("✓ Database tables ready")
    yield
    # (teardown logic would go here)


# ──────────────────────────────────────────────────────────
# App
# ──────────────────────────────────────────────────────────

app = FastAPI(
    title="College Admissions Prediction Market",
    description="""
A real-money-style prediction market for college admissions outcomes,
seeded by an XGBoost + Bayesian Inference ML model trained on 12,000+
real applicant records from r/collegeresults.

---

## Quick start

**1. Create an account** — `POST /users`
You receive `$1,000` in virtual credits and a user ID.

**2. Create a market** — `POST /markets`
Provide the school name and (optionally) student stats.  The ML model
automatically sets the opening probability.

**3. Trade** — `POST /markets/{id}/buy` or `/sell`
Buy YES shares (betting on admission) or NO shares (betting on rejection).
The LMSR market maker fills every order instantly.

**4. Resolve** — `POST /markets/{id}/resolve`
When the decision comes out, the creator resolves the market.
Winning shareholders receive **$1.00 per share**.

---

## Authentication

Protected endpoints require your user ID in the `X-User-Id` request header.
No passwords — the ID *is* the credential for now.

```
X-User-Id: <your-uuid>
```

---

## How prices work (LMSR)

The market maker uses the Logarithmic Market Scoring Rule:

```
current_price = e^(q_yes/b) / (e^(q_yes/b) + e^(q_no/b))
```

- `current_price` is always the live YES (admission) probability.
- Buying YES pushes the price up; buying NO pushes it down.
- The house subsidises liquidity; maximum house loss per market = `b × ln(2)`.
- The opening price is seeded from the ML model's prediction.
""",
    version="0.1.0",
    lifespan=lifespan,
)


# ──────────────────────────────────────────────────────────
# CORS — allow the Next.js frontend on any local port
# ──────────────────────────────────────────────────────────

_origins = ["http://localhost:3000", "http://localhost:3001"]
if _frontend_url := os.getenv("FRONTEND_URL"):
    _origins.append(_frontend_url.rstrip("/"))

app.add_middleware(
    CORSMiddleware,
    allow_origins=_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ──────────────────────────────────────────────────────────
# Routers
# ──────────────────────────────────────────────────────────

app.include_router(users.router)
app.include_router(markets.router)
app.include_router(trades.router)


# ──────────────────────────────────────────────────────────
# Utility endpoints
# ──────────────────────────────────────────────────────────

@app.get("/", include_in_schema=False)
async def root():
    return {
        "message": "College Admissions Prediction Market API",
        "docs":    "/docs",
        "redoc":   "/redoc",
    }


@app.get("/health", tags=["meta"], summary="Health check")
async def health():
    """Returns 200 OK if the server is running."""
    return {"status": "healthy"}
